### ISSUE TITLE
Update to 1.20.2 Please

### ISSUE THREAD

**Issue by sternschnaube** [DangoTown/ViewDimension#1]
I really wanna try this mod:)

**Comment by RTAkland** [comment]
sure, may be 2 hours later

**Comment by RTAkland** [comment]
actually, I don't have any PC with me. I will use gitpod to build a temp version for you

**Comment by RTAkland** [comment]
sorry about that I cant work without pc 🥸

**Comment by venaminecraft** [comment]
Sounds good, take your time please 😊

**Comment by venaminecraft** [comment]
Thanks already @RTAkland.

**Comment by RTAkland** [comment]
@sternschnaube Already updated to 1.20.2, go to release to download the latest version
